# Generated by Django 5.1.15 on 2026-03-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('detect_self_conflicts', models.BooleanField(default=True, help_text="Warn when a new event overlaps with the user's own events.")),
                ('detect_group_conflicts', models.BooleanField(default=False, help_text="Also check for overlaps with shared group members' events.")),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
