# Generated by Django 5.1.15 on 2026-03-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_eventrsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_id',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rrule',
            field=models.TextField(blank=True, default=''),
        ),
    ]
