# Generated by Django 5.1.15 on 2026-02-26 19:50

import django.db.models.deletion
import groups.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('boost_count', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('lv1', 'Level 1'), ('lv2', 'Level 2'), ('lv3', 'Level 3')], default='starter', max_length=10)),
                ('banner_url', models.TextField(blank=True, null=True)),
                ('bg_url', models.TextField(blank=True, null=True)),
                ('invite_code', models.CharField(default=groups.models.generate_invite_code, max_length=20, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('member', 'Member')], default='member', max_length=10)),
                ('share_mode', models.CharField(choices=[('all', 'All'), ('selective', 'Selective')], default='all', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
